image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
- port: 8002

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - command: service nginx start &
  - command: cd /workspace/magento2gitpod
  - command: /usr/sbin/php-fpm7.2 --fpm-config php-fpm.conf &
  - command: rm -f /etc/php/7.2/cli/conf.d/20-tideways.ini && rm -f /etc/php/7.2/fpm/conf.d/20-tideways.ini
  - command: cd /workspace/magento2gitpod && wget -c https://magento.mirror.hypernode.com/releases/magento-2.3.3.tar.gz
  - command: cd /workspace/magento2gitpod/ && cp default.vcl /etc/varnish && varnishd -F -T :6082 -t 120 -f /etc/varnish/default.vcl -s malloc,512m -p pipe_timeout=7200 -p default_ttl=3600 -p thread_pool_max=1000 -p cli_buffer=32k -p default_grace=3600 -p vcc_allow_inline_c=on -p thread_pool_min=50 -p workspace_client=512k -p thread_pool_timeout=120 -p http_resp_hdr_len=32k -p feature=+esi_ignore_other_elements &
